FROM ubuntu:24.04

SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

# Install system dependencies to build ROSA and run tests
RUN <<EOF
        export DEBIAN_FRONTEND=noninteractive

        # From https://github.com/zephyrproject-rtos/docker-image/blob/5f219dd531e6a8f021d43c8ea310db60fe0ebac6/Dockerfile.ci
        # Enable 32-bit package support for x86-64
	if [ "${HOSTTYPE}" = "x86_64" ]; then
		dpkg --add-architecture i386
	fi

        apt-get -y update
        apt-get -y upgrade

        apt-get install --no-install-recommends -y \
                wget \
                build-essential \
                python3 \
                python-is-python3 \
                python3-venv \
                python3-pip \
                ninja-build \
                file \
                git \
                jq \
                cmake \
                clang-tidy-16 \
                doxygen \
                graphviz \
                device-tree-compiler \
                xz-utils \
                libncurses-dev \
                unzip \
                curl \
                ca-certificates \
                iptables \
                iputils-ping \
                iproute2

        # Install x86-64 image-specific packages
	if [ "${HOSTTYPE}" = "x86_64" ]; then
		# Mark `python3` as held because APT otherwise tries to remove it during i386
		# package installation.
		apt-mark hold python3 python3-apt

		# Install multi-lib gcc
		apt-get install --no-install-recommends -y \
			gcc-multilib \
			g++-multilib

		# Install 32-bit dependencies
		apt-get install --no-install-recommends -y \
			libc6-dbg:i386 \
			libfuse-dev:i386 \
			libsdl2-dev:i386
	fi

         apt-get autoremove --purge -y
         apt-get clean -y
         rm -rf /var/lib/apt/lists/*
EOF


# Install Go toolchain for CUE compilation
ARG GO_VERSION=1.23.3
ARG GO_ARCH=amd64
RUN <<EOF
        cd /tmp
        wget -q https://go.dev/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz
        tar -C /usr/local -xzf go${GO_VERSION}.linux-${GO_ARCH}.tar.gz
        rm go${GO_VERSION}.linux-${GO_ARCH}.tar.gz
EOF
ENV PATH=/usr/local/go/bin:/root/go/bin:${PATH}
ENV GOPATH=/root/go


# Install CUE language tools
ARG CUE_VERSION=v0.10.1
RUN <<EOF
        go install cuelang.org/go/cmd/cue@${CUE_VERSION}
EOF


# Setup a python environment and install requirements
COPY resources/rosa-requirements.txt /tmp/rosa-requirements.txt
ARG ZEPHYR_UPSTREAM_TAG=v4.1.0
ARG ZEPHYR_UPSTREAM_URL=https://raw.githubusercontent.com/zephyrproject-rtos/zephyr
RUN <<EOF
        mkdir /venv
        python3 -m venv /venv
        . /venv/bin/activate

        pip install -r "${ZEPHYR_UPSTREAM_URL}/refs/tags/${ZEPHYR_UPSTREAM_TAG}/scripts/requirements.txt"
        pip install -r /tmp/rosa-requirements.txt
EOF
ENV PATH=/venv/bin:${PATH}


# Download and install Zephyr gcctoolchain & qemu for supported architectures
ARG SDK_ARCH=x86_64
ARG SDK_VERSION=0.17.0
RUN <<EOF
        mkdir -p /opt/toolchains
        cd /opt/toolchains
        wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${SDK_VERSION}"/zephyr-sdk-"${SDK_VERSION}"_linux-"${SDK_ARCH}"_minimal.tar.xz
        tar xf zephyr-sdk-"${SDK_VERSION}"_linux-"${SDK_ARCH}"_minimal.tar.xz
        ./zephyr-sdk-"${SDK_VERSION}"/setup.sh -t arm-zephyr-eabi -h
        rm ./*.tar.xz
EOF
ENV ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.17.0
ENV ZEPHYR_TOOLCHAIN_VARIANT=zephyr
